version: 2.1

orbs:
  python: circleci/python@0.2.1
  aws-cli: circleci/aws-cli@1.0.0
  node: circleci/node@4.7.0

jobs:
  checkout:
    docker:
      - image: node:14
    steps:
      - checkout
      - node/install:
          install-yarn: true
      - run: yarn
      - run: yarn dist


workflows:
  main:
    jobs:
      - checkout