# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- refs/tags/*

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.5'
  displayName: 'Install Node.js'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true
- task: Cache@2
  inputs:
    key: '"yarn" | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages
- script: |
    yarn
  displayName: 'Install NPM Packages'
- script: |
    GH_TOKEN=$(GH_TOKEN) yarn compile
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/'
    Contents: '*.dmg'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/'
    Contents: '*.exe'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(agent.builddirectory)/'
    Contents: '*.snap'
    TargetFolder: '$(build.artifactstagingdirectory)'
- task: GitHubRelease@1
  inputs:
    gitHubConnection: 'github.com_Hobart2967'
    repositoryName: '$(Build.Repository.Name)'
    action: 'edit'
    target: '$(Build.SourceVersion)'
    tag: '$(Build.SourceBranchName)'
    addChangeLog: false