# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- main
- devel

variables:
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn

pool:
  vmImage: 'macos-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '14.17.5'
  displayName: 'Install Node.js'
- task: YarnInstaller@3
  inputs:
    versionSpec: '1.x'
    checkLatest: true
- task: Cache@2
  inputs:
    key: '"yarn" | "$(Agent.OS)" | yarn.lock'
    restoreKeys: |
       yarn | "$(Agent.OS)"
    path: $(YARN_CACHE_FOLDER)
  displayName: Cache Yarn packages
- script: |
    yarn
  displayName: 'Install NPM Packages'
- script: |
    GH_TOKEN=$(GH_TOKEN) yarn dist -m -w -l
